app/face_features/models.py
from mongoengine import *


class FaceFeatures(Document):
    name = StringField(min_length=3)
    features = ListField(FloatField())

app/face_features/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileField, FileAllowed
from wtforms import FieldList, FormField, StringField, FloatField
from wtforms.validators import Length, DataRequired


class ImageForm(FlaskForm):
    image = FileField('Image', validators=[FileRequired(), FileAllowed(['gif', 'jpg', 'jpeg', 'png'],
                      'Only "gif", "jpg", "jpeg" and "png" files are supported')])


class FacesForm(FlaskForm):
    # TODO: due to issue with wtfforms form that contains nested forms cannot be serialised properly
    locations = FieldList(FloatField())
    names = FieldList(StringField(validators=[Length(3)]), validators=[DataRequired(), Length(1)])
    filename = StringField(validators=[DataRequired()])

    def validate(self):
        if not super().validate():
            return False

        if len(self.names.data) * 4 != len(self.locations.data):
            self.locations.errors.append('Each face should have four locations')
            return False

        return True

app/__init__.py
import wtforms_json
from flask import Flask
from flask_mongoengine import MongoEngine
from flask_wtf import CSRFProtect

from app.face_features.controllers import mod_face_features
from app.photos.controllers import mod_photos

BLUEPRINTS = [
    mod_face_features,
    mod_photos
]

db = MongoEngine()


def create_app(config=None, app_name=None):
    # if app_name is None:
    #     app_name = Config.DefaultConfig.PROJECT

    app = Flask(app_name)
    __configure_app(app, config)
    __configure_blueprints(app)
    __configure_extensions(app)

    return app


def __configure_app(app, config):
    app.config.from_pyfile('config.py')

    # MODE = os.getenv('APPLICATION_MODE', 'LOCAL')
    # print("Running in %s mode" % MODE)

    # app.config.from_envvar('YOURAPPLICATION_SETTINGS', True)

    if config:
        app.config.from_object(config)


def __configure_blueprints(app):
    for blueprint in BLUEPRINTS:
        app.register_blueprint(blueprint)


def __configure_extensions(app):
    # csrf
    csrf = CSRFProtect()
    csrf.init_app(app)

    db.init_app(app)

    # json forms
    wtforms_json.init()

app/face_features/controllers.py
import os

from flask import Blueprint, request, render_template, flash, redirect, url_for, jsonify

from app.decorators import ajax_required

from .helpers import save_uploaded_file, get_path_to_photo
from .face_detector import FaceDetectionService
from .forms import ImageForm, FacesForm
from .models import FaceFeatures

mod_face_features = Blueprint('face_features', __name__)
detector = FaceDetectionService()


@mod_face_features.route('/', methods=['GET', 'POST'])
def load_image():
    form = ImageForm()

    if request.method == 'POST' and form.validate_on_submit():
        path_to_saved_file = save_uploaded_file(form.image.data)
        face_locations = detector.get_face_locations_from_file(path_to_saved_file)
        if len(face_locations) > 0:
            return render_template('face_features/select-faces.html', face_locations=face_locations,
                                   image=os.path.basename(path_to_saved_file))
        else:
            flash('No faces found on your image', 'warning')

    return render_template('face_features/add-face.html', form=form)


@mod_face_features.route('/add_faces', methods=['POST'])
@ajax_required
def add_faces():
    form = FacesForm.from_json(request.json)
    if form.validate_on_submit():
        data = form.data
        face_features = detector.get_face_features(get_path_to_photo(data['filename']), data['locations'])

        entities = []
        for (features, name) in zip(face_features, data['names']):
            entities.append(FaceFeatures(name=name, features=features.tolist()))
        FaceFeatures.objects.insert(entities)

        return jsonify({'message': 'faces added successfully', 'status': 'success'}), 201

    return jsonify(form.errors), 400

app/photos/controllers.py
from flask import Blueprint, current_app, send_from_directory

import os

mod_photos = Blueprint('photos', __name__)


@mod_photos.route('/photos/<path:path>')
def index(path):
    photos_folder = os.path.join(current_app.instance_path, 'photos')
    return send_from_directory(photos_folder, path)

templates/face_features/add-face.html
{% extends "layout.html" %}
{% block body %}
    <form action="{{ url_for('face_features.load_image') }}" method=post class=add-entry enctype="multipart/form-data">
        {{ form.csrf_token }}

        <div class="row">
            <div class="form-group">
                 <div class="col-md-1">
                     {{ form.image.label }}
                     {{ form.image }}
                 </div>
            </div>
        </div>
        <div class="row">
            {% for field in form %}
                 {% for error in field.errors %}
                    <span class="alert alert-danger">{{ error }}</span>
                {% endfor %}
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>

{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

templates/face_features/select-faces.html
{% extends "layout.html" %}

{% block styles %}
{{ super() }}
<link href="{{url_for('static', filename='vendor/jquery-select-areas/resources/jquery.selectareas.css')}}"
      media="screen" rel="stylesheet" type="text/css"/>
<!--[if lte IE 8]>
<link href="{{url_for('static', filename='vendor/jquery-select-areas/resources/jquery.selectareas.ie8.css')}}"
      media="screen" rel="stylesheet" type="text/css"/>
<![endif]-->
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-8">
        <img id="img" src="{{url_for('photos.index', path=image)}}" class="img-responsive">
    </div>
    <div class="col-md-4">
        <form id="face-names" method="post" action="{{url_for('face_features.add_faces')}}">
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{url_for('static', filename='vendor/jquery-select-areas/jquery.selectareas.js')}}"></script>
<script type="text/javascript">
    (function () {
        var csrf_token = "{{ csrf_token() }}";
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            }
        });

        var faceLocations = {{face_locations | tojson | safe}};
        var areas = [];

        $(document).ready(function () {
            var $image = $('#img');

            var imageWidthRatio = $image.width() / $image.prop("naturalWidth");
            var imageHeightRatio = $image.height() /$image.prop("naturalHeight");

            areas = faceLocations.map(function (x) {
                var areaWidth = Math.abs(x[0] - x[2]) * imageWidthRatio;
                var areaHeight = Math.abs(x[1] - x[3]) * imageHeightRatio;

                return {
                    allowEdit: true,
                    x: x[3] * imageWidthRatio,// top
                    y: x[0] * imageHeightRatio,// right
                    height: areaHeight, // bottom
                    width: areaWidth// left
                };
            });

            $image.selectAreas({
                areas: areas,
                onLoaded: function () {
                    areas = $image.selectAreas('areas');
                    areas.forEach(function (x) {
                        addInput(x.id)
                    });
                },

                onChanged: function (event, id, selections) {
                    var added = $.grep(areas, function (e) { return e.id === id}).length === 0;
                    var deleted = $.grep(selections, function(e){ return e.id === id }).length === 0;
                    areas = selections;

                    if (!added && !deleted)
                        return;

                    if (deleted) {
                        $("#" + id).remove();
                    }

                    if (added) {
                        addInput(id)
                    }
                }
            });

            $('#face-names').submit(function (e) {
                e.preventDefault();
                faceNamesSubmit();
            });

            function faceNamesSubmit() {
                var $nameInputs = $('#face-names').find('input.form-control');
                var names = $.map($nameInputs, function (x) {
                    return $(x).val();
                });

                if (names.length !== areas.length)
                {
                    console.error('length of names not equals to length of areas');
                }
                else
                {
                    var locations = [];
                    for (var i = 0; i < areas.length; i++) {
                        locations = locations.concat(
                            [

                                areas[i].y / imageHeightRatio,
                                (areas[i].x + areas[i].width) / imageWidthRatio,
                                (areas[i].y + areas[i].height) / imageHeightRatio,
                                areas[i].x / imageWidthRatio
                            ]);
                    }

                    var data = {
                        filename: {{ image | tojson | safe }},
                        names: names,
                        locations: locations
                    };

                    $.ajax({
                        url: "{{url_for('face_features.add_faces')}}",
                        type: 'POST',
                        data: JSON.stringify(data),
                        contentType: 'application/json; charset=utf-8',
                        dataType: 'json',
                        success: function(data) {
                            alert(data.message);
                        }
                    });
                }
            }
        });

        function addInput(id) {
            $('<input/>', {
                id: id,
                name: 'faceNames[]',
                "class": 'form-control'
            }).insertBefore('#face-names > button');
        }
    })();
</script>
{% endblock %}

templates/layout.html
<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    {% block styles %}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='node_modules/bootstrap/dist/css/bootstrap.css') }}">
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for("face_features.load_image") }}">Face recognition</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <!--<li><a href="#about">About</a></li>-->
                <!--<li><a href="#contact">Contact</a></li>-->
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
        {% block body %}
        {% endblock %}
</div><!-- /.container -->
    {% block scripts %}
        <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.js') }}"></script>
        <script src="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.js') }}"></script>
    {% endblock %}
</body>
</html>